'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const cheerio=require('cheerio');
const BASE='https://www.paribucineverse.com';
const HALLS=[{id:1,name:'Paribu Cineverse MaviBahçe',district:'Karşıyaka',slug:'mavibahce'},{id:2,name:'Paribu Cineverse İzmir Park',district:'Konak',slug:'izmir-park'},{id:7,name:'Paribu Cineverse Forum Bornova',district:'Bornova',slug:'forum-bornova'},{id:8,name:'Paribu Cineverse Point Bornova',district:'Bornova',slug:'point-bornova'},{id:10,name:'Paribu Cineverse Karşıyaka Hilltown',district:'Karşıyaka',slug:'karsiyaka-hilltown'}];
const STORE=process.env.DATA_DIR?path.join(process.env.DATA_DIR,'data.json'):path.join(__dirname,'data.json');
const seed=path.join(__dirname,'data.json');
function readStore(){if(!fs.existsSync(STORE)){fs.mkdirSync(path.dirname(STORE),{recursive:true});fs.copyFileSync(seed,STORE);}const d=JSON.parse(fs.readFileSync(STORE,'utf8'));for(const k of ['cinemas','films','showtimes','prices'])if(!Array.isArray(d[k]))throw Error('Geçersiz veri dosyası: '+k);return d;}
function writeStore(d){fs.mkdirSync(path.dirname(STORE),{recursive:true});const temp=STORE+'.tmp';fs.writeFileSync(temp,JSON.stringify(d,null,2)+'\n');fs.renameSync(temp,STORE);}
const norm=s=>String(s||'').normalize('NFC').toLocaleLowerCase('tr-TR').replace(/\s+/g,' ').trim();
const hallName=s=>norm(s).replace(/\s*\(izmir\)$/u,'');
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const format=s=>clean(s).toLocaleUpperCase('tr-TR').replace(/\bALTY\b/g,'ALTYAZILI').replace(/\bDUB\b/g,'DUBLAJLI');
const MONTHS={'ocak':1,'şubat':2,'mart':3,'nisan':4,'mayıs':5,'haziran':6,'temmuz':7,'ağustos':8,'eylül':9,'ekim':10,'kasım':11,'aralık':12};
function parseDate(text){const m=clean(text).match(/^(\d{1,2})\s+([\p{L}]+)\s+(\d{4})\s*-\s*(\d{2}:\d{2})$/u);if(!m)throw Error('Seans tarihi okunamadı');const month=MONTHS[norm(m[2])];if(!month)throw Error('Tarih ayı okunamadı');const date=m[3]+'-'+String(month).padStart(2,'0')+'-'+m[1].padStart(2,'0');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(m[4])||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw Error('Geçersiz seans tarihi');return {date,time:m[4]};}
function parseCinema(html,hall){const $=cheerio.load(html);const heading=clean($('h1').first().text());if(hallName(heading)!==hallName(hall.name))throw Error('Sinema adı eşleşmedi');const sessions=new Map();$('[id="movieRow"][data-movie-title]').each((_,row)=>{const title=clean($(row).attr('data-movie-title'));$(row).find('a[data-url*="~session~"]').each((_,a)=>{const raw=$(a).attr('data-url');if(!/^\/biletleme\/~step~ticket~code~\d+~session~\d+$/.test(raw||''))return;const url=BASE+raw;const f=format($(a).closest('.row-area').find('.cinema-detail-tech-text').first().text());if(!title||!f)return;sessions.set(url,{url,title,format:f,time:clean($(a).text())});});});if(!sessions.size)throw Error('Seans bağlantıları bulunamadı; sayfa yapısı değişmiş olabilir');return {sessions:[...sessions.values()],address:clean($('h2').first().text())};}
function parseTicket(html,hall,expected){const $=cheerio.load(html);const info=$('.selected-content-info').first();const title=clean(info.find('.selected-content-title').text()),location=clean(info.find('.selected-content-location').text());if(norm(title)!==norm(expected.title)||hallName(location)!==hallName(hall.name))throw Error('Bilet sayfasında film/sinema eşleşmedi');const dt=parseDate(info.find('.selected-content-date').attr('datetime')||info.find('.selected-content-date').text());const f=format(info.find('.selected-content-other-info').text());if(!f||dt.time!==expected.time)throw Error('Bilet sayfasında format/saat eşleşmedi');const prices=[];$('.ticket-flow-2-option-info-wrap').each((_,e)=>{const label=norm($(e).find('.ticket-flow-2-option-title').text());const type=/^tam(?:\s|$)/u.test(label)?'full':/^öğrenci(?:\s|$)/u.test(label)?'student':null;const text=clean($(e).find('.ticket-flow-2-option-price').text());const m=text.match(/^(\d+(?:\.\d{3})*(?:,\d{1,2})?)\s*TL$/);if(!type||!m)return;const amount=Number(m[1].replace(/\./g,'').replace(',','.'));if(amount>0&&Number.isFinite(amount))prices.push({ticketType:type,ticketLabel:clean($(e).find('.ticket-flow-2-option-title').text()),amount});});return {...dt,title,format:f,prices};}
async function getHTML(url){const u=new URL(url);if(u.origin!==BASE)throw Error('Kaynak alan adı desteklenmiyor');const response=await fetch(url,{signal:AbortSignal.timeout(20000),redirect:'error',headers:{'User-Agent':'IzmirSinema/1.2 (public showtime and price comparison)','Accept':'text/html'}});if(!response.ok)throw Error('Kaynak HTTP '+response.status);const text=await response.text();if(text.length>2500000)throw Error('Kaynak çok büyük');return text;}
async function pool(items,workers,fn){const results=new Array(items.length);let index=0;await Promise.all(Array.from({length:Math.min(workers,items.length)},async()=>{while(index<items.length){const i=index++;try{results[i]={ok:true,value:await fn(items[i])};}catch(e){results[i]={ok:false,error:e.message,item:items[i]};}}}));return results;}
let running=null,lastAttempt=0;
const status=()=>({running:!!running,lastAttempt:lastAttempt?new Date(lastAttempt).toISOString():null});
async function collect(options={}){if(running)return running;if(!options.force&&Date.now()-lastAttempt<30*60*1000)return {skipped:true,reason:'Kaynaklar son 30 dakika içinde kontrol edildi.'};lastAttempt=Date.now();running=perform(options).finally(()=>{running=null;});return running;}
async function perform(options){const d=readStore();const checkedAt=new Date().toISOString();const sources=[];const fetchHTML=options.fetchHTML||getHTML;const halls=options.halls||HALLS;let count=0;
 for(const hall of halls){const sourceUrl=BASE+'/sinemalar/'+hall.slug;const state={cinemaId:hall.id,name:hall.name,sourceUrl,attemptedAt:checkedAt,status:'error',showtimeCount:0,priceCount:0};
 try{const page=parseCinema(await fetchHTML(sourceUrl),hall);const results=await pool(page.sessions,3,async s=>{const html=await fetchHTML(s.url);return {s,parsed:parseTicket(html,hall,s),hash:crypto.createHash('sha256').update(html).digest('hex'),checkedAt:new Date().toISOString()};});
 const success=results.filter(r=>r.ok);if(!success.length)throw Error('Bilet sayfaları okunamadı: '+(results[0]?.error||'Bilinmeyen hata'));
 // Replace only sessions that were successfully checked. Failed sessions keep their previous records and timestamps.
 for(const result of success){const {s,parsed,hash,checkedAt:at}=result.value;let film=d.films.find(f=>norm(f.title)===norm(parsed.title));if(!film){film={id:Math.max(0,...d.films.map(f=>Number(f.id)||0))+1,title:parsed.title};d.films.push(film);}
 const session=s.url.match(/~session~(\d+)/)[1];const id='paribu-'+hall.id+'-'+session;d.showtimes=d.showtimes.filter(x=>!((x.provider==='paribu'&&x.id===id)||(String(x.cinemaId)===String(hall.id)&&String(x.filmId)===String(film.id)&&x.date===parsed.date&&x.time===parsed.time&&format(x.format)===parsed.format)));
 d.showtimes.push({id,cinemaId:hall.id,filmId:film.id,date:parsed.date,time:parsed.time,format:parsed.format,sourceUrl:s.url,sourceCheckedAt:at,provider:'paribu'});
 d.prices=d.prices.filter(p=>p.showtimeId!==id);
 for(const p of parsed.prices)d.prices.push({...p,id:id+'-'+p.ticketType,showtimeId:id,cinemaId:hall.id,filmId:film.id,date:parsed.date,time:parsed.time,format:parsed.format,currency:'TRY',sourceUrl:s.url,verified:true,checkedAt:at,provider:'paribu',sourceHash:hash,note:'Resmî bilet kategorisi: '+p.ticketLabel+'. Resmî bilet seçimi sayfası. Koltuk ve hizmet bedeli nedeniyle ödeme adımında değişebilir.'});
 state.priceCount+=parsed.prices.length;state.showtimeCount++;count+=parsed.prices.length;}
 // On a complete scan remove obsolete sessions for observed dates. Partial scans never delete unchecked records.
 if(success.length===page.sessions.length){const dates=new Set(success.map(r=>r.value.parsed.date));const ids=new Set(success.map(r=>'paribu-'+hall.id+'-'+r.value.s.url.match(/~session~(\d+)/)[1]));d.showtimes=d.showtimes.filter(s=>s.cinemaId!==hall.id||!dates.has(s.date)||ids.has(s.id));d.prices=d.prices.filter(p=>p.cinemaId!==hall.id||!dates.has(p.date)||(p.provider==='paribu'&&ids.has(p.showtimeId)));}
 let cinema=d.cinemas.find(c=>c.id===hall.id);if(!cinema){cinema={...hall};delete cinema.slug;d.cinemas.push(cinema);}Object.assign(cinema,{address:page.address,sourceUrl,verified:true,checkedAt});delete cinema.status;
 state.status=success.length===page.sessions.length?(state.priceCount?'ok':'no_prices'):'partial';state.failedCount=results.length-success.length;state.errors=results.filter(r=>!r.ok).slice(0,3).map(r=>r.error);state.checkedAt=new Date().toISOString();
 }catch(e){state.error=e.message;}sources.push(state);console.log(hall.name+': '+state.status+' · '+state.priceCount+' fiyat');
 // Save progress between halls so restarts cannot discard an entire successful scan.
 d.sources=[...(d.sources||[]).filter(s=>s.cinemaId!==hall.id),state];writeStore(d);
 }
 const update={at:new Date().toISOString(),priceCount:count,sources:sources.map(s=>({cinemaId:s.cinemaId,status:s.status,priceCount:s.priceCount}))};d.updates=[update,...(d.updates||[])].slice(0,30);writeStore(d);return update;
}
function startScheduler(){const timer=setInterval(()=>collect().catch(e=>console.error('Toplama:',e.message)),6*60*60*1000);timer.unref();setTimeout(()=>collect().catch(e=>console.error('Toplama:',e.message)),1500).unref();}
if(require.main===module)collect({force:true}).then(r=>{console.log(JSON.stringify(r));if(!r.priceCount)process.exitCode=1;}).catch(e=>{console.error(e.message);process.exitCode=1;});
module.exports={readStore,collect,status,startScheduler,parseCinema,parseTicket,parseDate,HALLS};
